### ISSUE TITLE
Fix link in the docs

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gov-docs#12]
The deploy your own DAO button redirects to gov-ui instead of gov-deployer. 

https://w3hc.github.io/gov-docs/deployment.html

**Comment by erikacheyenne** [comment]
@julienbrg Can I be assigned to work on this issue?

**Comment by chahmedejaz** [comment]
Hey @julienbrg  - Hope you are doing good! I would to pick this issue for the fix. Thanks.

**Comment by erikacheyenne** [comment]
Thank you, I've gone ahead and created this PR https://github.com/w3hc/gov-docs/pull/15

**Comment by julienbrg** [comment]
Fixed by @erikacheyenne with https://github.com/w3hc/gov-docs/pull/15
